base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns=[
    path('',  views.home, name="home"),
    path('space/<str:pk>', views.space, name="space"),
    path('create-space/', views.createspace, name="create_space")
]

connectandlearn/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Space(models.Model):

    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic= models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    # participants =
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Message(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    space = models.ForeignKey(Space, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from .models import Space


class SpaceForm(ModelForm):
    class Meta:
        model = Space
        fields = '__all__'

base/views.py
from django.shortcuts import render, redirect
from .models import Space
from .forms import SpaceForm

# Create your views here.

def home(request):

    spaces = Space.objects.all()
    
    context = {'spaces': spaces}

    return render(request, 'home.html', context)

def space(request, pk):

    name = Space.objects.get(id=pk)

    context = {'space': name}

    return render( request, 'space.html' ,context)


def createspace(request):

    form = SpaceForm()
    if request.method == "POST":
        form = SpaceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('base:home')

    context = {'form': form}

    return render(request, 'room_form.html', context)


def updatespace(request):
    pass

def deletespace(request, pk):
    pass

base/templates/home.html
{% extends 'main.html' %}

{% block content %}

<div>

    <a href="{% url 'base:create_space' %}">Create Space</a>

    <div>
        {% for space in spaces %}
            <div>
                <span>@{{space.host.username}}</span>
                <h1>{{space.id}}. <a href="{% url 'base:space' space.id%}">{{space.name}}</a></h1>
                <small>{{space.topic.name}}</small>
                <hr>
            </div>
        {% endfor %}
    </div>
</div>
    

{% endblock %}

base/templates/room_form.html
{% extends 'main.html' %}

{% block content %}

    <div>
        <form method="Post" action="">
            {% csrf_token%}
                {{form.as_p}}
            <input type="submit" value="Submit" />
        </form>
    </div>

{% endblock %}

base/templates/space.html
{% extends 'main.html' %}

{% block content %}

    <h1>Description</h1>
    <h1>   -{{space.description}}</h1>

{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connect&Learn</title>
</head>
<body>
    {% include 'nav.html' %}

    {% block content %}
    {% endblock %}

</body>
</html>

templates/nav.html
<a href="{% url 'base:home' %}">
    <h1>LOGO</h1>
</a>